Issue #338: build failure on macOS and Windows
Generating gegl's gir docs gives an error:
ERROR: Could not find GIR dependency in the search paths: Babl-0.1

It seems we need to add the path to Babl's gir file to the include path
for the API doc generation.