meson: fix npd functions inaccessible from GIMP
Recently our GIMP builds started failing with errors like:
undefined reference to `npd_get_control_point_with_radius_at'.

A recent change in gegl set gegl_npd_lib as libraries_private. However,
the npd library needs to be accessible outside of gegl, e.g. in GIMP.
Changing this back to adding gegl_npd_lib to libraries, fixes this.